export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER"
export const GET_LOGGEDIN_USER="GET_LOGGEDIN_USER";
export const GET_SELECTED_ADDRESS = "GET_SELECTED_ADDRESS";
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";