export default {
    primaryBackGround:'#F8F8F8',
	primaryTextColor:'#FF0539',    
    primaryTextColor2:'#007520',
    primaryButtonColor:'#00A82D',
    primaryButtonTitleColor:'white',
    primaryButtonTitleColor2:'#007520',
    primaryHeaderColor:'#00A82D',

    primaryPlaceholderTextColor:'#7176A0',
    primaryTextInputColor:'#B4B6CB',
    primaryTextInputBorderBottomColor:'#515CAA',
    primaryHeaderIconColor:'white',
    primaryButtonBackGroundColor:'#17A2D4',
    primaryButtonBorderColor:'#33649F',
    primaryButtonBackGroundColor2:'#EEEEEE',
    primaryButtonBorderColor2:'#33649F',
    primaryButtonFontColor:'white',
    primaryListItemsBackGroundColor:'#303665',
    primaryWarningBackGroundColor:'#FFF2CC',
    primaryListItemBorderColor:'#23284B',
    primaryActivityIndicatorColor:'white',
    primaryTextLinkBackgroundColor:'#CCCCCC',
    primaryModalBackgroundColor:'#003366',
    primaryModalBorderColor:'#5C6283',
}